language: dart

dart:
  - "2.1.1"
  - "2.2.0"
  - "2.3.2"
  - "2.4.1"
  - "2.5.1"
  - "2.6.1"
  - "2.7.2"
  - stable
  - dev

jobs:
  allow_failures:
    - dart: 2.6.1
    - dart: dev
  fast_finish: true

dart_task:
  - test
  - dartfmt
  - dartanalyzer: --fatal-warnings .

cache:
  directories:
    - $HOME/.pub-cache
