language: dart

dart:
  - "2.7.2"
  - stable
  - dev

jobs:
  allow_failures:
    - dart: dev
  fast_finish: true

dart_task:
  - test
  - dartfmt
  - dartanalyzer: --fatal-warnings .

cache:
  directories:
    - $HOME/.pub-cache
