name: math_expressions
version: 2.0.1
homepage: https://github.com/fkleon/math-expressions
description: >-
  A library for parsing and evaluating mathematical expressions, supporting real
  numbers, vectors, and basic interval arithmetic.

dependencies:
  vector_math: ^2.1.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety

environment:
  sdk: '>=2.1.1 <3.0.0'
